apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres-metrics
    type: postgres
    access: proxy
    url: aws-1-us-east-1.pooler.supabase.com:5432
    database: postgres
    user: postgres.ouogetytffnkwjdiqjxv
    secureJsonData:
      password: ser516metrics
    jsonData:
      sslmode: require
      postgresVersion: 15
    isDefault: false
    editable: true
